version: "3.9"

services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://db:5432/vitpred
      - KC_DB_USERNAME=postgres
      - KC_DB_PASSWORD=postgres-password
      - KC_DB_SCHEMA=keycloak
    ports:
      - "8080:8080"
    depends_on:
      - db
    # volumes:
    #   - ./keycloak/:/opt/jboss/keycloak/standalone/data/
    command: ["start-dev"]

  db:
    image: postgres:15
    environment:
      - POSTGRES_PASSWORD=postgres-password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=vitpred
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql
      - ./sql:/docker-entrypoint-initdb.d

